import type { IndexRecord } from '@shared/types'

/**
 * The 8 notes of `desktop/src/main/fs/viewsFixture.ts` as `getIndex()` records, rooted at `/vault`, with
 * size/ctime/mtime zeroed (GRO-2128). `vaultIndex/live.test.ts` deep-equals the real scan to this list,
 * so client-side Bases tests and the main-process index share one truth. Sorted by path.
 */
export const TEST_RECORDS: IndexRecord[] = [
  {
    path: '/vault/Content Pillars/1. Agentic Agency/Agentic Agency.md',
    name: 'Agentic Agency.md',
    basename: 'Agentic Agency',
    folder: 'Content Pillars/1. Agentic Agency',
    ext: 'md',
    size: 0,
    ctime: 0,
    mtime: 0,
    properties: {
      pillar: 'Agentic Agency',
      status: 'idea',
      priority: 2,
      tags: ['agentic', 'pillar'],
      published: false,
      date: '2026-08-01',
    },
    aliases: [],
    tags: ['agentic', 'pillar'],
    links: [],
    embeds: [],
  },
  {
    path: '/vault/Content Pillars/1. Agentic Agency/The Levels of an Agency.md',
    name: 'The Levels of an Agency.md',
    basename: 'The Levels of an Agency',
    folder: 'Content Pillars/1. Agentic Agency',
    ext: 'md',
    size: 0,
    ctime: 0,
    mtime: 0,
    properties: {
      pillar: 'Agentic Agency',
      status: 'drafting',
      priority: 1,
      tags: ['agentic/levels'],
      cover: '[[levels.png]]',
      related: '[[Agentic Agency]]',
    },
    aliases: [],
    tags: ['agentic/levels'],
    links: ['levels.png', 'Agentic Agency'],
    embeds: [],
  },
  {
    path: '/vault/Content Pillars/2. Creator Economy/Creator Economy.md',
    name: 'Creator Economy.md',
    basename: 'Creator Economy',
    folder: 'Content Pillars/2. Creator Economy',
    ext: 'md',
    size: 0,
    ctime: 0,
    mtime: 0,
    properties: {
      pillar: 'Creator Economy',
      status: 'published',
      priority: 3,
      published: true,
      date: '2026-07-15',
      views: 12000,
    },
    aliases: [],
    tags: [],
    links: [],
    embeds: [],
  },
  {
    path: '/vault/Content Pillars/2. Creator Economy/The Gold In Your Archive.md',
    name: 'The Gold In Your Archive.md',
    basename: 'The Gold In Your Archive',
    folder: 'Content Pillars/2. Creator Economy',
    ext: 'md',
    size: 0,
    ctime: 0,
    mtime: 0,
    properties: { pillar: 'Creator Economy', status: 'idea', tags: 'creator' },
    aliases: [],
    tags: ['creator'],
    links: [],
    embeds: [],
  },
  {
    path: '/vault/Content Pillars/3. Trust Economy & Paid Ads/Attribution.md',
    name: 'Attribution.md',
    basename: 'Attribution',
    folder: 'Content Pillars/3. Trust Economy & Paid Ads',
    ext: 'md',
    size: 0,
    ctime: 0,
    mtime: 0,
    properties: {},
    aliases: [],
    tags: ['attribution'],
    links: [],
    embeds: ['chart.png'],
  },
  {
    path: '/vault/Content Pillars/4. Tech & Silicon Valley/Tech & Silicon Valley.md',
    name: 'Tech & Silicon Valley.md',
    basename: 'Tech & Silicon Valley',
    folder: 'Content Pillars/4. Tech & Silicon Valley',
    ext: 'md',
    size: 0,
    ctime: 0,
    mtime: 0,
    properties: {},
    frontmatterError: 'Flow sequence in block collection must be sufficiently indented and end with a ]',
    aliases: [],
    tags: [],
    links: [],
    embeds: [],
  },
  {
    path: '/vault/Content Pillars/List of Topics.md',
    name: 'List of Topics.md',
    basename: 'List of Topics',
    folder: 'Content Pillars',
    ext: 'md',
    size: 0,
    ctime: 0,
    mtime: 0,
    properties: {},
    aliases: [],
    tags: ['pillars'],
    links: ['Agentic Agency', 'Creator Economy'],
    embeds: [],
  },
  {
    path: '/vault/VSL-v1.md',
    name: 'VSL-v1.md',
    basename: 'VSL-v1',
    folder: '',
    ext: 'md',
    size: 0,
    ctime: 0,
    mtime: 0,
    properties: { status: 'published', pillar: null },
    aliases: [],
    tags: [],
    links: [],
    embeds: [],
  },
]

