import type { BridgeError } from '@shared/types'

/** IPC channel names shared by main and preload. One place, so a typo cannot split them. */
export const CH = {
  fsTree: 'fs:tree',
  fsRead: 'fs:read',
  fsReadPdf: 'fs:read-pdf',
  fsReadImage: 'fs:read-image',
  fsWrite: 'fs:write',
  fsCreateDir: 'fs:create-dir',
  fsCreateFile: 'fs:create-file',
  fsIndex: 'fs:index',
  fsColdDiff: 'fs:cold-diff',
  fsReadAsset: 'fs:read-asset',
  fsWriteAsset: 'fs:write-asset',
  fsRename: 'fs:rename',
  fsDelete: 'fs:delete',
  fsClip: 'fs:clip',
  fsPaste: 'fs:paste',
  fsClipState: 'fs:clip-state',
  fileRepairRename: 'file:repair-rename',
  fileRenamed: 'file:renamed',
  fileDeleted: 'file:deleted',
  clipChanged: 'clip:changed',
  shellReveal: 'shell:reveal',
  shellOpenVsCode: 'shell:openVsCode',
  shellOpenDefault: 'shell:openDefault',
  shellOpenLink: 'shell:open-link',
  shellAgentPrompt: 'shell:agent-prompt',
  dialogPickFolder: 'dialog:pick-folder',
  watchSubscribe: 'watch:subscribe',
  watchUnsubscribe: 'watch:unsubscribe',
  watchEvent: 'watch:event',
  stateGet: 'state:get',
  stateSetSettings: 'state:set-settings',
  stateSetSidebarWidth: 'state:set-sidebar-width',
  statePushRecent: 'state:push-recent',
  stateRemoveRecent: 'state:remove-recent',
  stateSetFolder: 'state:set-folder',
  stateSetFolds: 'state:set-folds',
  stateSetBaseGroups: 'state:set-base-groups',
  stateChanged: 'state:changed',
  windowIdentity: 'window:identity',
  windowSetIdentity: 'window:set-identity',
  windowOpen: 'window:open',
  windowDuplicate: 'window:duplicate',
  windowOpenRecent: 'window:open-recent',
  windowCloseSelf: 'window:close-self',
  windowZoom: 'window:zoom',
  menuPasteAs: 'menu:paste-as',
  menuCopyAs: 'menu:copy-as',
  menuCopyText: 'menu:copy-text',
  menuPasteTextFallback: 'menu:paste-text-fallback',
  menuOpenFolder: 'menu:open-folder',
  menuOpenRoot: 'menu:open-root',
  menuSearch: 'menu:search',
  menuSwitchVault: 'menu:switch-vault',
  menuSettings: 'menu:settings',
  menuToggleSidebar: 'menu:toggle-sidebar',
  menuZoom: 'menu:zoom',
  menuCloseTab: 'menu:close-tab',
  menuNextTab: 'menu:next-tab',
  menuPrevTab: 'menu:prev-tab',
  linkOpenFile: 'link:open-file',
  linkNotice: 'link:notice',
  vaultConfigRead: 'vaultConfig:read',
  vaultConfigWrite: 'vaultConfig:write',
  vaultConfigChanged: 'vaultConfig:changed',
  propertiesGet: 'properties:get',
  propertiesSetProperty: 'properties:set-property',
  propertiesRemoveProperty: 'properties:remove-property',
  propertiesChanged: 'properties:changed',
  favoritesGet: 'favorites:get',
  favoritesSet: 'favorites:set',
  favoritesChanged: 'favorites:changed',
  githubStatus: 'github:status',
  githubSyncNow: 'github:sync-now',
  githubSetEnabled: 'github:set-enabled',
  githubStatusChanged: 'github:status-changed',
  appFlush: 'app:flush',
  appFlushed: 'app:flushed',
} as const

/**
 * Every `ipcMain.handle` answers with an envelope: Electron serialises a thrown Error down to
 * its message, so a structured `BridgeError` must travel as data. The preload unwraps it.
 */
export type Envelope<T> = { ok: true; value: T } | { ok: false; error: BridgeError }
